### PR TITLE
Quick fix for custom destruct cursor.

### PR DESCRIPTION
**Pull request by JorisVanEijden**
This works for the current special case of the destruct cursor. When there's a need for multiple different cursors a separate CursorManager class will be better https://www.youtube.com/watch?v=hV4fBMRRbRw

### CODE REVIEW

**Comment by jellewie** [comment]
I have rewritten and patch it using your code. It's now combined with the master, 
But I forgot to first merge it, so it's now in conflict and such (I'm still quite new to this concept) so sorry but this. Although the code is used, I can't mark it as a resolved branch

**Comment by jellewie** [comment]
the 'Destroy(InHand);' in '_DeconstructTool' (should be?) needed to stop building and start deconstructing.

(You removed the line in your code, was it by accident or was I wrong?)

**Comment by JorisVanEijden** [comment]
That's ok. Learning and progressing is the goal right?
I moved the `Destroy(InHand)` to only be called when switching `DeconstructToolEquiped` on, not off.
I'll close this PR since it's not needed anymore.

**Comment by jellewie** [comment]
@JorisVanEijden haven't though about it that way, you are right btw.
Not sure how I did do it now but it won't hurt to check how it's at the master atm so (I) will try to check it soon.

**Pull request closed without merging**
